export const provinceCitiesMap = {
    Punjab: [
      "Ahmadpur East",
      "Ahmed Nager Chatha",
      "Ali Khan Abad",
      "Alipur",
      "Arifwala",
      "Attock",
      "Bhera",
      "Bhalwal",
      "Bahawalnagar",
      "Bahawalpur",
      "Bhakkar",
      "Burewala",
      "Chillianwala",
      "Chakwal",
      "Chichawatni",
      "Chiniot",
      "Chishtian",
      "Daska",
      "Darya Khan",
      "Dera Ghazi Khan",
      "Dhaular",
      "Dina",
      "Dinga",
      "Dipalpur",
      "Faisalabad",
      "Fateh Jang",
      "Ghakhar Mandi",
      "Gojra",
      "Gujranwala",
      "Gujrat",
      "Gujar Khan",
      "Hafizabad",
      "Haroonabad",
      "Hasilpur",
      "Haveli Lakha",
      "Jalalpur Jattan",
      "Jampur",
      "Jaranwala",
      "Jhang",
      "Jhelum",
      "Kalabagh",
      "Karor Lal Esan",
      "Kasur",
      "Kamalia",
      "Kāmoke",
      "Khanewal",
      "Khanpur",
      "Kharian",
      "Khushab",
      "Kot Adu",
      "Jauharabad",
      "Lahore",
      "Lalamusa",
      "Layyah",
      "Liaquat Pur",
      "Lodhran",
      "Malakwal",
      "Mamoori",
      "Mailsi",
      "Mandi Bahauddin",
      "Mian Channu",
      "Mianwali",
      "Multan",
      "Murree",
      "Muridke",
      "Mianwali Bangla",
      "Muzaffargarh",
      "Narowal",
      "Okara",
      "Renala Khurd",
      "Pakpattan",
      "Pattoki",
      "Pir Mahal",
      "Qaimpur",
      "Qila Didar Singh",
      "Rabwah",
      "Raiwind",
      "Rajanpur",
      "Rahim Yar Khan",
      "Rawalpindi",
      "Sadiqabad",
      "Safdarabad",
      "Sahiwal",
      "Sangla Hill",
      "Sarai Alamgir",
      "Sargodha",
      "Shakargarh",
      "Sheikhupura",
      "Sialkot",
      "Sohawa",
      "Soianwala",
      "Siranwali",
      "Talagang",
      "Taxila",
      "Toba Tek Singh",
      "Vehari",
      "Wah Cantonment",
      "Wazirabad",
    ],
    Sindh: [
      "Badin",
      "Bhirkan",
      "Rajo Khanani",
      "Chak",
      "Dadu",
      "Digri",
      "Diplo",
      "Dokri",
      "Ghotki",
      "Haala",
      "Hyderabad",
      "Islamkot",
      "Jacobabad",
      "Jamshoro",
      "Jungshahi",
      "Kandhkot",
      "Kandiaro",
      "Karachi",
      "Kashmore",
      "Keti Bandar",
      "Khairpur",
      "Kotri",
      "Larkana",
      "Matiari",
      "Mehar",
      "Mirpur Khas",
      "Mithani",
      "Mithi",
      "Mehrabpur",
      "Moro",
      "Nagarparkar",
      "Naudero",
      "Naushahro Feroze",
      "Naushara",
      "Nawabshah",
      "Nazimabad",
      "Qambar",
      "Qasimabad",
      "Ranipur",
      "Ratodero",
      "Rohri",
      "Sakrand",
      "Sanghar",
      "Shahbandar",
      "Shahdadkot",
      "Shahdadpur",
      "Shahpur Chakar",
      "Shikarpaur",
      "Sukkur",
      "Tangwani",
      "Tando Adam Khan",
      "Tando Allahyar",
      "Tando Muhammad Khan",
      "Thatta",
      "Umerkot",
      "Warah",
    ],
    Balochistan: [
      "Quetta",
      "Khuzdar",
      "Turbat",
      "Chaman",
      "Hub",
      "Sibi",
      "Zhob",
      "Gwadar",
      "Dera Murad Jamali",
      "Dera Allah Yar",
      "Usta Mohammad",
      "Loralai",
      "Pasni",
      "Kharan",
      "Mastung",
      "Nushki",
      "Kalat",
    ],
    "Khyber Pakhtunkhwa": [
      "Abbottabad",
      "Adezai",
      "Alpuri",
      "Akora Khattak",
      "Ayubia",
      "Banda Daud Shah",
      "Bannu",
      "Batkhela",
      "Battagram",
      "Birote",
      "Chakdara",
      "Charsadda",
      "Chitral",
      "Daggar",
      "Dargai",
      "Darya Khan",
      "Dera Ismail Khan",
      "Doaba",
      "Dir",
      "Drosh",
      "Hangu",
      "Haripur",
      "Karak",
      "Kohat",
      "Kulachi",
      "Lakki Marwat",
      "Latamber",
      "Madyan",
      "Mansehra",
      "Mardan",
      "Mastuj",
      "Mingora",
      "Nowshera",
      "Paharpur",
      "Pabbi",
      "Peshawar",
      "Saidu Sharif",
      "Shorkot",
      "Shewa Adda",
      "Swabi",
      "Swat",
      "Tangi",
      "Tank",
      "Thall",
      "Timergara",
      "Tordher",
    ],
    "Gilgit-Baltistan": [
      "Gilgit",
      "Skardu",
      "Khaplu",
      "Dambudas",
      "Tolti",
      "Kharmang",
      "Eidghah",
      "Shigar",
      "Nagarkhas",
      "Ishkoman",
      "Juglot",
      "Danyor",
      "Karimabad",
      "Aliabad",
      "Chilas",
      "Gahkuch",
      "Tangir",
    ],
    "Azad Jammu & Kashmir": [
      "Muzaffarabad",
      "Mirpur",
      "Rawalakot",
      "Kotli",
      "Dhirkot",
      "Bagh",
      "Hajira",
      "Bhimbar",
      "Palandri",
      "Chakswari",
    ],
  };

  export type Province = keyof typeof provinceCitiesMap;